apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-demo
  template:
    metadata:
      labels:
        app: secret-demo
    spec:
      containers:
        - name: secret-demo
          image: busybox
          command: ["/bin/sh","-c"]
          args:
            - while true; do
                echo "USER=$DB_USER";
                echo "PASS=$DB_PASSWORD";
                sleep 10;
              done
          envFrom:
            - secretRef:
                name: db-secret
          volumeMounts:
            - name: secret-vol
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: secret-vol
          secret:
            secretName: db-secret
