apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-html
data:
  index.html: |
    <html>
      <head><title>Hello K8s</title></head>
      <body style="font-family: sans-serif;">
        <h1>Hello from a ConfigMap 👋</h1>
        <p>If you can read this, you successfully mounted a ConfigMap as a file.</p>
      </body>
    </html>
