apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hello-routes
  namespace: learn
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`hello.learn.local`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: api-service
          port: 80
    - match: Host(`hello.learn.local`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: hello-service
          port: 80
